### ISSUE TITLE
Néhány kör adatlapja - körvezetőként nézve - hibát dob

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#57]
valami svie állapot furcsaság lehet:
korok/showgroup/id/56

```
 Message: Could not find component 'adminOrActive:form:table:body:rows:56:cells:4:cell:msAsImg' on page 'class hu.sch.web.kp.group.ShowGroup

Root cause:

org.apache.wicket.core.request.handler.ComponentNotFoundException: Could not find component 'adminOrActive:form:table:body:rows:56:cells:4:cell:msAsImg' on page 'class hu.sch.web.kp.group.ShowGroup
     at org.apache.wicket.core.request.handler.PageAndComponentProvider.getComponent(PageAndComponentProvider.java:182)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.getComponent(ListenerInterfaceRequestHandler.java:90)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:231)
```

**Comment by vbalazs** [comment]
nem tudom reprodukálni :(

**Comment by tmichel** [comment]
próbáltad nem adminként?

**Comment by vbalazs** [comment]
a hiba körvezetőként jelentkezett. elképzelhető, hogy cache para. nehéz lesz reprodukálni.

**Comment by vbalazs** [comment]
egyelőre hagyjuk.
