### ISSUE TITLE
SVIE ikon megjelenítés bugfix, átalakítás

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#74]
Érkezett egy automatikus bugreport, ami szerint körvezetőként megnézve a Dezső buli kört, a SVIE állapotokat mutató ikonok közül legalább egy nem jelent meg rendesen.

Ezt a funkciót anno elég zavarosan valósítottam meg, sajnos került logika a User domain classba is: https://github.com/kir-dev/korok/blob/master/sch-pek-domain/src/main/java/hu/sch/domain/user/User.java#L263

A web rétegben próbáltam egy külön komponensbe kitenni, de ezek szerint még mindig generál hibákat, a stacktrace alapján megtalálható.

URL: https://korok.sch.bme.hu/korok/showgroup/id/56
Stacktrace:

```
 Message: Could not find component 'adminOrActive:form:table:body:rows:310:cells:4:cell:msAsImg' on page 'class hu.sch.web.kp.group.ShowGroup

Root cause:

org.apache.wicket.core.request.handler.ComponentNotFoundException: Could not find component 'adminOrActive:form:table:body:rows:310:cells:4:cell:msAsImg' on page 'class hu.sch.web.kp.group.ShowGroup

     at org.apache.wicket.core.request.handler.PageAndComponentProvider.getComponent(PageAndComponentProvider.java:182)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.getComponent(ListenerInterfaceRequestHandler.java:90)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:231)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:861)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
     at com.sun.identity.agents.filter.AmAgentBaseFilter.allowRequestToContinue(AmAgentBaseFilter.java:130)
     at com.sun.identity.agents.filter.AmAgentBaseFilter.doFilter(AmAgentBaseFilter.java:80)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:397)
     at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
     at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:165)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:372)
     at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:505)
     at org.apache.coyote.ajp.AjpProtocol$AjpConnectionHandler.process(AjpProtocol.java:453)
     at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:931)
     at java.lang.Thread.run(Thread.java:744)
```

**Comment by tmichel** [comment]
Úgy tűnik, hogy wicket bugot sikerült fogni.

A hiba előidézhető, ha körvezetőként megnézzük egy kör oldalát, a tagokat felsoroló táblázatot rendezzük, majd újrarendezzük anélkül, hogy megvárnánk, hogy az előző kérés teljesen lefusson.

Úgy tűnik, hogy a wicket nem tudja lekezelni, hogy egy azon adathalmazon (az ajaxos táblázat csak a memóriában rendezi db query által visszaadott adathalmazt) több kérés párhuzamosan módosításokat végez.

Egy _quick and dirty_ próbálkozás tettem arra, hogy szálbiztossá tegyem a rendezést, de ez nem oldotta meg a problémát. Valahol mélyebben lehet ennek a gyökere a wicketen belül.

Egyelőre lezárom ezt a issue-t, mert a valós probléma (wicket ajaxos táblázat hiányosságai) megoldása túl messzire vezetne. A front-end újraíráskor ez probléma megszűnik majd.
