### ISSUE TITLE
Pont és belépőértékelés mentése nagy létszámú köröknél

### ISSUE THREAD

**Issue by vbalazs** [kir-dev/korok#82]
Az a helyzet, hogy a konténer HTTP lib (jboss esetén tomcat?) korlátozza a request paraméterek számát, alapértelmezetten 512-ben.

Ez az olyan nagy köröknél, mint pl. az SSSL, ahol ennél több aktív tag van, az értékelések mentése exceptiont dob.

<pre>
java.lang.IllegalStateException: More than the maximum number of request parameters (GET plus POST) for a single request ([512]) were detected. Any parameters beyond this limit have been ignored. To change this limit, set the maxParameterCount attribute on the Connector.
     at org.apache.tomcat.util.http.Parameters.addParameter(Parameters.java:199)
     at org.apache.tomcat.util.http.Parameters.processParameters(Parameters.java:383)
     at org.apache.tomcat.util.http.Parameters.processParameters(Parameters.java:229)
     at org.apache.catalina.connector.Request.parseParameters(Request.java:2874)
     at org.apache.catalina.connector.Request.getParameterNames(Request.java:1333)
     at org.apache.catalina.connector.Request.getParameterMap(Request.java:1313)
     at org.apache.catalina.connector.RequestFacade.getParameterMap(RequestFacade.java:422)
     at org.apache.wicket.protocol.http.servlet.ServletWebRequest.generatePostParameters(ServletWebRequest.java:293)
</pre>

**Comment by vbalazs** [comment]
Megoldás: https://community.jboss.org/thread/198502?_sscc=t

**Comment by vbalazs** [comment]
konfig install doksiba visszavezetve
