### ISSUE TITLE
NPE a legördülő választónál a körök története oldalon

### ISSUE THREAD

**Issue by tmichel** [kir-dev/korok#83]
Ez a hiba már máskor is jelentkezett. Talán volt ahol javításra is került. 

```
java.lang.NullPointerException
     at hu.sch.web.kp.group.GroupHistory$1.onSelectionChanged(GroupHistory.java:96)
     at hu.sch.web.kp.group.GroupHistory$1.onSelectionChanged(GroupHistory.java:85)
     at org.apache.wicket.markup.html.form.DropDownChoice.onSelectionChanged(DropDownChoice.java:215)
     at java.lang.reflect.Method.invoke(Method.java:606)
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:240)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:226)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:861)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
```

A hiba azért jelentkezik, mert valahogy sikerül az üres opciót választani és a [`selected` paraméter `null` lesz](https://github.com/kir-dev/korok/blob/master/sch-pek-web/src/main/java/hu/sch/web/kp/group/GroupHistory.java#L96). Egy null-check szerintem megteszi, és némi jelzés a felhasználónak, hogy hiba történt, válasszon újra.

**Comment by Ksisu** [comment]
Két helyen használja így:
https://github.com/kir-dev/korok/blob/master/sch-pek-web/src/main/java/hu/sch/web/kp/group/GroupHistory.java#L96
https://github.com/kir-dev/korok/blob/master/sch-pek-web/src/main/java/hu/sch/web/kp/valuation/Valuations.java#L129

Valamint egy másik helyen van még valami hasonló, de ott nem így használja(lehet hogy itt volt javítva?).
https://github.com/kir-dev/korok/blob/master/sch-pek-web/src/main/java/hu/sch/web/kp/user/UserHistory.java#L107

**Comment by Ksisu** [comment]
Nos a felső két esetben van egy olyan opció is, hogy: "Choose One". Ha kiválasztunk egyet és mielőtt betöltene visszaváltunk rá akkor dobja a hibát. Az alsónál más a helyzet, ott nincs ilyen lehetőség, így ott nem keletkezik hiba.

**Comment by tmichel** [comment]
menjen a merge a masterbe és zárd le az issue-t
